apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bookstore
  template:
    metadata:
      labels:
        app: bookstore
    spec:
      containers:
      - name: bookstore
        image: zaidaneafaf/bookstore-app:1.0
        ports:
        - containerPort: 8080
        env:
        - name: DB_URL
          value: "jdbc:mysql://mysql-service:3306/bookstore?allowPublicKeyRetrieval=true&useSSL=false"
        - name: DB_USER
          value: "bookstore_user"
        - name: DB_PASSWORD
          value: "password"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
        - name: MYSQL_DATABASE
          value: "bookstore"
        - name: MYSQL_USER
          value: "bookstore_user"
        - name: MYSQL_PASSWORD
          value: "password"